# XCODE
#
# define macro to set library properties for Mac OS X
# FRAMEWORK					create OS X library framework
# INSTALL_NAME_DIR			value for Xcode INSTALL_PATH variable
# BUILD_WITH_INSTALL_RPATH	make sure INSTALL_PATH gets set 
#

IF(APPLE AND ${CMAKE_GENERATOR} STREQUAL "Xcode")
	SET(GENERATE_FOR_XCODE ON)
ELSE(APPLE AND ${CMAKE_GENERATOR} STREQUAL "Xcode")
	SET(GENERATE_FOR_XCODE OFF)
ENDIF(APPLE AND ${CMAKE_GENERATOR} STREQUAL "Xcode")

IF(GENERATE_FOR_XCODE)
	OPTION(FRAMEWORK_SUPPORT "If ON shared libraries will be created as frameworks on Mac OS X" ON)
	OPTION(FRAMEWORK_BUILD_WITH_INSTALL_RPATH "Sets install_name property of shared libraries on Mac OS X" ON)
ENDIF(GENERATE_FOR_XCODE)

MACRO(SET_XCODE_FRAMEWORK_PROPERTIES name)
	IF(GENERATE_FOR_XCODE)
		SET_TARGET_PROPERTIES(${name} PROPERTIES
			FRAMEWORK ${FRAMEWORK_SUPPORT}
			XCODE_ATTRIBUTE_DYLIB_COMPATIBILITY_VERSION "${PXLMAJORRELEASEVERSION}.${PXLMINORRELEASEVERSION}"
			MACOSX_FRAMEWORK_SHORT_VERSION_STRING "${PXLMAJORRELEASEVERSION}.${PXLMINORRELEASEVERSION}"
			BUILD_WITH_INSTALL_RPATH ${FRAMEWORK_BUILD_WITH_INSTALL_RPATH}
			INSTALL_NAME_DIR "./"
			INSTALL_RPATH_USE_LINK_PATH ON)
	ENDIF(GENERATE_FOR_XCODE)
ENDMACRO(SET_XCODE_FRAMEWORK_PROPERTIES name)

#               
# create universal binaries on OS X
# make sure libraries are compatible with OS X Snow Leopard (10.6)
#
IF(GENERATE_FOR_XCODE)
	SET(CMAKE_OSX_ARCHITECTURES "i386;x86_64")
	SET(CMAKE_OSX_SYSROOT /Developer/SDKs/MacOSX10.6.sdk)
ENDIF(GENERATE_FOR_XCODE)

#
# display status information to user
# 
MESSAGE(STATUS "GENERATE_FOR_XCODE = ${GENERATE_FOR_XCODE}")
IF(GENERATE_FOR_XCODE)
	MESSAGE(STATUS "FRAMEWORK_SUPPORT = ${FRAMEWORK_SUPPORT}")
	MESSAGE(STATUS "FRAMEWORK_BUILD_WITH_INSTALL_RPATH = ${FRAMEWORK_BUILD_WITH_INSTALL_RPATH}")
ENDIF(GENERATE_FOR_XCODE)